# Generated by Django 4.2.3 on 2023-07-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collections',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='src.collection'),
        ),
    ]
