# Generated by Django 4.2.3 on 2023-07-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_profile_collections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_pass',
            new_name='id_user',
        ),
    ]
