# Generated by Django 4.2.3 on 2023-07-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rename_id_pass_profile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collections',
        ),
    ]
