# Generated by Django 4.2.3 on 2023-07-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_post_user_obj_alter_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_obj',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='src.profile'),
        ),
    ]
