# Generated by Django 4.2.3 on 2023-07-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
