# Generated by Django 4.2.3 on 2023-07-21 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_remove_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.profile'),
        ),
    ]
