# Generated by Django 4.2.3 on 2023-07-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_post_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='prof',
        ),
        migrations.AddField(
            model_name='post',
            name='user_obj',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
