# Generated by Django 4.2.3 on 2023-07-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_remove_post_prof_post_user_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_obj',
            new_name='user_obj_id',
        ),
    ]
