# Generated by Django 4.2.3 on 2023-07-21 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0014_rename_user_obj_post_user_obj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_obj_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
