# Generated by Django 4.2.3 on 2023-07-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_alter_post_user_obj_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_obj_id',
        ),
        migrations.AddField(
            model_name='track',
            name='trackLol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
