# Generated by Django 4.2.3 on 2023-07-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_post_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
